import type {Metadata} from 'next'
import Image from 'next/image'
import Link from 'next/link'
import {PageHero} from '@/components/PrototypePages'
import {blogPosts} from '@/lib/blog'

export const metadata:Metadata={title:'Blog técnico de cromatografía | SOLINSA',description:'Métodos, mantenimiento, consumibles y cumplimiento explicados por ingenieros de aplicaciones y servicio.'}

export default async function Page({searchParams}:{searchParams:Promise<{categoria?:string}>}){const {categoria}=await searchParams; const categories=[...new Set(blogPosts.map(post=>post.category))]; return <><PageHero crumb="Conocimiento" eyebrow="Blog técnico" title="Notas técnicas escritas por quien da el servicio." lead="Métodos, mantenimiento, consumibles y cumplimiento. Lo que resolvemos en laboratorios reales, explicado para que puedas aplicarlo en el tuyo."/><section className="section"><div className="container hero-grid"><div style={{position:'relative',overflow:'hidden',borderRadius:'var(--radius)',minHeight:320}}><Image src="/images/blog-hplc-mantenimiento.png" alt="Ingeniero revisando un sistema HPLC en el laboratorio" fill sizes="(max-width: 900px) 100vw, 50vw" style={{objectFit:'cover'}} /></div><div className="stack"><span className="badge blue">Mantenimiento</span><h2>Siete señales de que tu HPLC necesita servicio antes de detenerse.</h2><p className="lead">Presión errática, ruido en la línea base y picos que se ensanchan sin haber cambiado la columna. Qué revisar, en qué orden y cuándo conviene detener el equipo por decisión propia y no por una falla.</p><Link className="text-link" href="/blog/siete-senales-hplc-servicio">Leer el artículo →</Link></div></div></section><section className="section tint"><div className="container stack-lg"><div className="row between responsive"><h2>Publicaciones recientes</h2><a className="text-link" href="#categorias">Ver todas las categorías →</a></div><nav id="categorias" className="row responsive" aria-label="Categorías del blog"><a href="/blog#categorias">Todas</a>{categories.map(category=><a key={category} aria-current={categoria===category?'page':undefined} href={`/blog?categoria=${encodeURIComponent(category)}#categorias`}>{category}</a>)}</nav><div className="grid-3">{blogPosts.filter(post=>post.slug!=='siete-senales-hplc-servicio' && (!categoria || post.category===categoria)).map(post=><Link className="card" href={`/blog/${post.slug}`} key={post.slug}><span className="badge">{post.category}</span><h4>{post.title}</h4><p>{post.summary}</p><span className="caps">{post.date} · {post.readTime}</span></Link>)}</div></div></section><section className="section dark"><div className="container row between responsive"><div className="stack"><h2>Cuéntanos el síntoma y el modelo. Respondemos con criterio técnico.</h2><p className="lead">Respuesta técnica en menos de 2 horas en horario laboral.</p></div><a className="btn btn-wa" href="https://wa.me/522201432743">Escríbenos por WhatsApp</a></div></section></>}
