import type {Metadata} from 'next'
import Link from 'next/link'
import {PageHero} from '@/components/PrototypePages'
import {getBlogPosts} from '@/lib/blog'

export const metadata:Metadata={title:'Blog técnico de cromatografía | SOLINSA',description:'Métodos, mantenimiento, consumibles y cumplimiento explicados por ingenieros de aplicaciones y servicio.'}

export const revalidate = 3600

export default async function Page({searchParams}:{searchParams:Promise<{categoria?:string}>}){const {categoria}=await searchParams; const posts=await getBlogPosts(); const categories=[...new Set(posts.map(post=>post.category))]; return <><PageHero crumb="Conocimiento" eyebrow="Blog técnico" title="Notas técnicas escritas por quien da el servicio." lead="Métodos, mantenimiento, consumibles y cumplimiento. Lo que resolvemos en laboratorios reales, explicado para que puedas aplicarlo en el tuyo."/><section className="section tint"><div className="container stack-lg"><div className="row between responsive"><h2>Publicaciones recientes</h2><a className="text-link" href="#categorias">Ver todas las categorías →</a></div><nav id="categorias" className="row responsive" aria-label="Categorías del blog"><Link href="/blog#categorias">Todas</Link>{categories.map(category=><Link key={category} aria-current={categoria===category?'page':undefined} href={`/blog?categoria=${encodeURIComponent(category)}#categorias`}>{category}</Link>)}</nav><div className="grid-3">{posts.filter(post=>!categoria || post.category===categoria).map(post=><Link className="card" href={`/blog/${post.slug}`} key={post.slug}><span className="badge">{post.category}</span><h4>{post.title}</h4><p>{post.summary}</p><span className="caps">{post.date} · {post.readTime}</span></Link>)}</div></div></section><section className="section dark"><div className="container row between responsive"><div className="stack"><h2>Cuéntanos el síntoma y el modelo. Respondemos con criterio técnico.</h2><p className="lead">Respuesta técnica en menos de 2 horas en horario laboral.</p></div><a className="btn btn-wa" href="https://wa.me/522201432743">Escríbenos por WhatsApp</a></div></section></>}
