import Link from 'next/link'
const WA='https://wa.me/528123554766'
const offers=[
  {n:'01',title:'Proyectos llave en mano',text:'Para el laboratorio que necesita una capacidad analítica nueva y no solo una cotización de equipo.',items:['Configuración propuesta','Requerimientos del sitio','Puesta en marcha y capacitación'],href:'/soluciones'},
  {n:'02',title:'Montaje de técnicas y métodos',text:'Del equipo instalado al método trabajando: columna, detector, preparación de muestra y condiciones.',items:['Selección de configuración','Ajuste de condiciones','Transferencia al personal'],href:'/industrias'},
  {n:'03',title:'Servicio técnico multimarca',text:'Mantenimiento, correctivo, calificaciones y contratos. Revisamos la viabilidad según marca, modelo y condición.',items:['Reporte con pruebas de cierre','IQ, OQ y PQ según alcance','Contratos por parque de equipos'],href:'/servicio'},
]
const families=[['Cromatografía de gases y GC-MS','Equipos, detectores, automuestreadores y preparación de muestras: purga y trampa, desorción térmica y pirólisis.','GC · GC-MS · PFPD · TEA · VUV','/soluciones/gc-gcms'],['HPLC y UHPLC','Sistemas, detectores UV, DAD, RID, FL y ELSD, y columnas.','HPLC · UHPLC · UV · DAD · RID','/soluciones/hplc-uhplc'],['Cromatografía iónica','Aniones, cationes y configuraciones con supresión.','IC · ANIONES · CATIONES','/soluciones/ic'],['Espectroscopía y análisis elemental','UV-Vis, FTIR y absorción atómica.','UV-VIS · FTIR · AA','/soluciones'],['Preparación de muestras','Purga y trampa, pirólisis, headspace y digestión por microondas.','P&T · PYROLYSIS · HEADSPACE','/soluciones'],['Sistemas de agua','Calidad de salida declarada, capacidad y condiciones de alimentación.','TIPO I · TIPO II','/soluciones'],['Consumibles y refacciones','Columnas, viales, septas, lámparas y bibliotecas espectrales.','COLUMNAS · VIALES · REFACCIONES','/soluciones/consumibles']]
const steps=[['1','Revisión del objetivo','Analito, matriz, norma, número de muestras y límite requerido.'],['2','Configuración','Equipo, detector, columna y preparación de muestra.'],['3','Instalación','Requerimientos del sitio, puesta en marcha e IQ/OQ.'],['4','Montaje','Condiciones, curva, verificación y transferencia.'],['5','Operación','Capacitación, consumibles y servicio programado.']]
export default function HomePage(){return <>
  <header className="hero surface"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">Integración y servicio multimarca</span><h1>Tu proyecto de cromatografía, desde la configuración hasta la puesta en marcha.</h1><p className="lead">Integramos equipos, montamos métodos en tu laboratorio y damos servicio técnico multimarca. Un acompañamiento que conecta tu aplicación con la operación diaria.</p><div className="stack"><a className="btn btn-wa" style={{width:'max-content'}} href={`${WA}?text=Hola%2C%20quiero%20orientaci%C3%B3n%20para%20un%20proyecto%20de%20instrumentaci%C3%B3n%20en%20mi%20laboratorio.`}>Platicar mi proyecto por WhatsApp</a><span className="muted small">Puedes escribirnos aunque aún no sepas qué equipo necesitas.</span></div><div className="row responsive"><Link className="text-link" href="/soluciones">Explorar productos →</Link><Link className="text-link" href="/servicio">Conocer nuestro servicio →</Link></div></div><div className="stack"><div className="placeholder"><strong>Fotografía pendiente</strong><span>Ingeniero de Solinsa trabajando en un sistema instalado, con sus accesorios visibles.</span></div><span className="small muted">Pie de foto: identificar equipo, laboratorio y actividad realizada. Sin fotografías genéricas de laboratorio.</span></div></div></header>
  <section className="section tint"><div className="container stack-lg"><div className="stack" style={{maxWidth:'760px'}}><span className="eyebrow">Qué hacemos</span><h2>El diferenciador no es el equipo. Es quién lo mantiene corriendo.</h2></div><div className="grid-3">{offers.map(o=><article className="card accent" key={o.title}><span className="icon">{o.n}</span><h4>{o.title}</h4><p>{o.text}</p><span className="caps">Qué entrega Solinsa</span><ul className="feature-list">{o.items.map(i=><li key={i}>{i}</li>)}</ul><Link href={o.href} className="text-link">Ver detalle →</Link></article>)}</div></div></section>
  <section className="section"><div className="container stack-lg"><div className="row between responsive"><div className="stack"><span className="eyebrow">Casos de éxito</span><h2>Han resuelto una situación parecida a la mía.</h2></div><Link href="/sobre-nosotros" className="text-link">Ver todos los casos →</Link></div><div className="grid-2">{[['Bebidas alcohólicas · HPLC · Integración','Integración de HPLC para furfural y azúcares en un laboratorio de bebidas alcohólicas','Suministro e instalación de HPLC con UV y RID, selección de columnas, montaje, IQ/OQ y capacitación.'],['Alimentos y confitería · GC · HPLC','Optimización de GC y HPLC en un laboratorio de alimentos y confitería','Diagnóstico de instalación, intervención multimarca y ajuste de condiciones de trabajo.']].map(c=><article className="card" key={c[1]}><div className="placeholder" style={{minHeight:190}}><strong>Fotografía pendiente</strong><span>Fotografía real del sistema y la actividad realizada.</span></div><span className="badge blue">{c[0]}</span><h4>{c[1]}</h4><p>{c[2]}</p><Link href="/sobre-nosotros" className="text-link">Ver el caso completo →</Link></article>)}</div></div></section>
  <section className="section tint"><div className="container stack-lg"><div className="stack"><span className="eyebrow">Encuentra tu ruta</span><h2>Encuentra lo que necesita tu laboratorio.</h2></div><div className="grid-4">{[['Implementar una aplicación','Sé qué necesito medir, no qué equipo comprar.','/industrias'],['Buscar un equipo o consumible','Catálogo por técnica, tipo de producto y fabricante.','/soluciones'],['Atender una falla','Un equipo detenido o con resultados fuera de criterio.','/servicio/correctivo'],['Planear mantenimiento o calificaciones','Preventivo, IQ/OQ/PQ y contratos anuales.','/servicio']].map((x,i)=><Link className="card" href={x[2]} key={x[0]}><span className="icon">0{i+1}</span><h4>{x[0]}</h4><p>{x[1]}</p><span className="text-link">Ver detalle →</span></Link>)}</div></div></section>
  <section className="section dark"><div className="container stack-lg"><div className="stack"><span className="eyebrow">Cómo trabajamos</span><h2>Cinco etapas, del requerimiento a la operación diaria.</h2></div><div className="steps">{steps.map(s=><div className="step" key={s[0]}><span className="step-num">{s[0]}</span><h4>{s[1]}</h4><p>{s[2]}</p></div>)}</div></div></section>
  <section className="section"><div className="container stack-lg"><div className="row between responsive"><div className="stack"><span className="eyebrow">Productos</span><h2>Familias del catálogo, con cromatografía al frente.</h2></div><Link className="text-link" href="/soluciones">Ver catálogo completo →</Link></div><div className="grid-3">{families.map(f=><Link className="card" href={f[3]} key={f[0]}><span className="caps">{f[2]}</span><h4>{f[0]}</h4><p>{f[1]}</p><span className="text-link">Explorar familia →</span></Link>)}</div></div></section>
  <section className="section tint"><div className="container stack-lg"><div className="stack"><span className="eyebrow">Proveedores</span><h2>Tecnologías que integramos según tu aplicación.</h2></div><div className="grid-4">{[['Young In Chromass','GC, HPLC/UHPLC y sistemas de agua'],['Wasson-ECE','GC configurados a medida y detección PFPD'],['QTEK','GC-MS y opciones de espectrometría'],['VUV Analytics','Detección VUV y soluciones por aplicación'],['EST Analytical','Purga y trampa'],['CDS Analytical','Pirólisis y preparación de muestras'],['Ellutia','Detección TEA y configuraciones de GC'],['Shine','Cromatografía iónica']].map(b=><article className="card" key={b[0]}><span className="caps">Tecnología</span><h4>{b[0]}</h4><p>{b[1]}</p></article>)}</div><Link href="/sobre-nosotros" className="text-link">Ver todos los proveedores →</Link></div></section>
  <section className="section"><div className="container grid-2"><div className="stack"><span className="eyebrow">Por qué Solinsa</span><h2>Un integrador técnico, no solo un vendedor de equipos.</h2><p className="lead">Detrás de cada instalación hay ingenieros de aplicaciones y de servicio con nombre, función y especialidad. Son quienes montan el método y quienes vuelven cuando el equipo lo necesita.</p><Link href="/sobre-nosotros" className="text-link">Conocer a Solinsa →</Link></div><div className="placeholder"><strong>Fotografía pendiente</strong><span>Equipo técnico de Solinsa en una instalación real.</span></div></div></section>
  <section className="section tint"><div className="container stack-lg"><div className="stack"><span className="eyebrow">Recursos</span><h2>Tres piezas para llevarte hoy.</h2></div><div className="grid-3"><Link className="card" href="/industrias/alimentos"><span className="badge blue">Ficha de aplicación</span><h4>Compuestos orgánicos volátiles en matrices ambientales por GC-MS</h4><p>Componentes de una configuración para VOCs y los criterios a revisar antes de definir preparación de muestra y columna.</p><span className="caps">Referencia de método · EPA 8260D</span></Link><Link className="card" href="/recursos"><span className="badge">Recurso en preparación</span><h4>Datos que conviene reunir antes de comprar una columna</h4><p>Checklist para registrar muestra, analitos, fase actual y dimensiones antes de pedir una referencia.</p><span className="caps">Aún sin archivo disponible</span></Link><Link className="card" href="/blog/siete-senales-hplc-servicio"><span className="badge">Artículo</span><h4>Qué debe incluir un proyecto de cromatografía llave en mano</h4><p>Componentes, responsabilidades y entregables que conviene acordar antes de instalar un sistema.</p><span className="caps">Selección e integración · 7 min</span></Link></div></div></section>
  <section className="section dark"><div className="container row between responsive"><div className="stack"><span className="eyebrow">Hablemos</span><h2>Cuéntanos qué necesitas resolver.</h2><p className="lead">Revisaremos la aplicación o el equipo y te indicaremos qué información necesitamos para avanzar.</p></div><a className="btn btn-wa" href={WA}>Conversar por WhatsApp</a></div></section>
</>}
