import Link from 'next/link'
export {ProductCatalog} from './ProductCatalog'
const WA='https://wa.me/528123554766'
export function PageHero({crumb='Inicio',eyebrow,title,lead,cta}:{crumb?:string,eyebrow?:string,title:string,lead:string,cta?:string}){return <header className="page-hero"><div className="container"><span className="breadcrumbs"><Link href="/">Inicio</Link> · {crumb}</span>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1><p className="lead">{lead}</p>{cta&&<a className="btn btn-wa" style={{width:'max-content'}} href={WA}>{cta}</a>}</div></header>}
const Empty=({text='Fotografía del equipo pendiente'}:{text?:string})=><div className="placeholder"><strong>Fotografía pendiente</strong><span>{text}</span></div>
const Card=({title,text,meta,href='#'}:{title:string,text:string,meta?:string,href?:string})=><Link href={href} className="card">{meta&&<span className="badge blue">{meta}</span>}<h4>{title}</h4><p>{text}</p><span className="text-link">Ver detalle →</span></Link>

import {productFamilies} from '@/lib/products'

export function ProductDetail({slug='hplc-uhplc'}:{slug?:string}){
  const p = productFamilies[slug] ?? productFamilies['hplc-uhplc']
  const faqLd = {'@context':'https://schema.org','@type':'FAQPage',mainEntity:p.faq.map(f=>({'@type':'Question',name:f.q,acceptedAnswer:{'@type':'Answer',text:f.a}}))}
  return <>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({
    '@context':'https://schema.org','@type':'Product',name:p.title,brand:p.brand,description:p.lead,url:`https://www.solinsa.mx/soluciones/${p.slug}`,category:p.kind
  })}} />
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(faqLd)}} />
  <PageHero crumb={`Productos · ${p.kind}`} eyebrow={p.eyebrow} title={p.title} lead={p.lead} cta={p.whatsappCta}/>
  <section className="section"><div className="container hero-grid"><Empty text={p.photoAlt}/><div className="stack-lg"><span className="eyebrow">Configuración por aplicación</span><h2>{p.sectionTitle}</h2><ul className="feature-list">{p.features.map(f=><li key={f}>{f}</li>)}</ul><p className="muted">{p.footnote}</p></div></div></section>
  <section className="section tint"><div className="container stack-lg"><div className="stack"><span className="eyebrow">Aplicaciones</span><h2>Aplicaciones documentadas</h2><p className="lead">Cada ficha explica la ruta técnica y su fuente. La idoneidad del equipo para tu analito, matriz y objetivo se establece en la revisión de la aplicación.</p></div><div className="grid-3">{p.applications.map(a=><Card meta={a.source} title={a.title} text={a.text} key={a.title}/>)}</div></div></section>
  <section className="section"><div className="container grid-2"><div className="stack"><h2>Especificaciones</h2><table className="data-table"><tbody>{p.specs.map(r=><tr key={r[0]}><td>{r[0]}</td><td className="mono">{r[1]}</td></tr>)}</tbody></table></div><div className="stack-lg"><article className="card accent"><h4>Instalación</h4><p>Revisión de requerimientos, instalación, puesta en marcha y pruebas de cierre.</p><Link href="/recursos" className="text-link">Checklist de preparación del sitio →</Link></article><article className="card"><h4>Respaldo Solinsa</h4><p>Capacitación, montaje de métodos, mantenimiento y calificaciones según alcance.</p></article><article className="card"><h4>Preguntas frecuentes</h4><div className="stack">{p.faq.map(f=><details key={f.q}><summary>{f.q}</summary><p className="muted">{f.a}</p></details>)}</div></article></div></div></section>
  </>}

const serviceData=[['Mantenimiento preventivo','Intervención programada, limpieza, inspección, reemplazo por desgaste y pruebas de cierre.','/servicio/preventivo'],['Mantenimiento correctivo','Diagnóstico de una falla, propuesta de intervención, reparación y pruebas de cierre.','/servicio/correctivo'],['Calificaciones IQ, OQ y PQ','Protocolos y ejecución según el alcance documental y operativo del laboratorio.','/servicio/iq-oq-pq'],['Contratos de servicio','Plan anual para un parque de equipos, con calendario, alcances y prioridades.','/servicio'],['Capacitación','Operación, mantenimiento de usuario y transferencia de métodos al personal.','/servicio'],['Atención de emergencia','Primera revisión del síntoma y prioridad según criticidad y disponibilidad.','/servicio/emergencia']]
export function Services(){return <><PageHero crumb="Servicios" eyebrow="Servicio técnico multimarca" title="Servicio técnico para sostener la operación de tu laboratorio." lead="Mantenimiento preventivo y correctivo, calificaciones IQ/OQ/PQ, contratos y capacitación. Revisamos la viabilidad del servicio según marca, modelo, condición y alcance."/><section className="section dark"><div className="container row between responsive"><div className="stack"><h2>¿Un equipo detenido o con fallas?</h2><p className="lead">Cuéntanos el síntoma y el modelo. No necesitas completar un formulario para pedir ayuda.</p></div><a className="btn btn-wa" href={WA}>Reportar una falla por WhatsApp</a></div></section><section className="section"><div className="container stack-lg"><span className="eyebrow">Directorio de servicios</span><div className="grid-3">{serviceData.map((s,i)=><Link className="card accent" href={s[2]} key={s[0]}><span className={`icon ${i===1?'gold':''}`}>0{i+1}</span><h4>{s[0]}</h4><p>{s[1]}</p><span className="text-link">Ver detalle →</span></Link>)}</div></div></section><section className="section tint"><div className="container grid-2"><div className="placeholder"><strong>Fotografía pendiente</strong><span>Ingeniero durante una intervención real, con equipo y actividad identificables.</span></div><div className="stack"><span className="eyebrow">Multimarca</span><h2>Atendemos equipos que no vendimos.</h2><p className="lead">Revisamos marca, modelo, antigüedad, condición y disponibilidad de refacciones antes de confirmar el alcance.</p><a className="btn btn-wa" style={{width:'max-content'}} href={WA}>Consultar viabilidad</a></div></div></section></>}

export function ServiceDetail({title='Mi equipo tiene una falla, ¿pueden ayudarme?',mode='correctivo'}:{title?:string,mode?:string}){const flow=mode==='correctivo'?[['1','Primera conversación','Síntoma, marca, modelo y efecto sobre la operación.'],['2','Revisión de viabilidad','Historial, disponibilidad y condiciones para diagnosticar.'],['3','Diagnóstico','Inspección y pruebas para identificar la causa.'],['4','Propuesta','Alcance, refacciones, tiempo estimado y pruebas de cierre.']]:[['1','Levantamiento','Equipo, configuración, uso e historial.'],['2','Alcance','Actividades, refacciones y documentación.'],['3','Intervención','Ejecución en sitio y registro técnico.'],['4','Cierre','Pruebas, reporte y recomendaciones.']];return <><PageHero crumb="Servicios" eyebrow="Mantenimiento correctivo" title={title} lead="Sí. Empieza por describirnos el síntoma. Con eso revisamos si podemos atender el equipo y qué diagnóstico corresponde." cta="Reportar una falla por WhatsApp"/><section className="section"><div className="container stack-lg"><div className="stack"><span className="eyebrow">Proceso</span><h2>Cómo es el recorrido</h2><p className="lead">Un diagnóstico inicial no es una reparación confirmada. La intervención se propone después de revisar el equipo.</p></div><div className="grid-4">{flow.map(x=><article className="card" key={x[0]}><span className="icon">{x[0]}</span><h4>{x[1]}</h4><p>{x[2]}</p></article>)}</div></div></section><section className="section tint"><div className="container grid-2"><div className="stack"><h2>Qué nos ayuda saber</h2><p className="lead">Nada de esto es obligatorio para escribirnos. Si lo tienes a la mano, acelera la primera conversación.</p><ul className="feature-list"><li>Marca, modelo y número de serie</li><li>Mensaje de error o síntoma observado</li><li>Último mantenimiento o intervención</li><li>Fotografías, cromatogramas o bitácora</li></ul><Link href="/recursos" className="text-link">Guía: información útil para reportar una falla →</Link></div><Empty text="Ingeniero de Solinsa durante el diagnóstico de un equipo en planta."/></div></section><section className="section"><div className="container grid-2"><div className="stack"><span className="eyebrow">Preguntas frecuentes</span><h2>Preguntas frecuentes</h2></div><div className="stack"><article className="card"><h4>¿El diagnóstico incluye la reparación?</h4><p>No. El diagnóstico identifica la causa y las piezas que puede requerir la intervención. La reparación se propone después, con su alcance y refacciones descritos.</p></article><article className="card"><h4>¿Atienden equipos que no vendieron?</h4><p>Sí, sujeto a revisión de marca, modelo, condición y disponibilidad de refacciones.</p></article></div></div></section></>}

export function Industries(){const inds=[['Bebidas alcohólicas','Furfural, azúcares, alcoholes superiores y perfiles de destilado.','HPLC · GC · UV · RID','/industrias/alimentos'],['Alimentos y bebidas','Conservadores, edulcorantes, aromas, contaminantes y control de calidad.','HPLC · GC-MS · VUV','/industrias/alimentos'],['Ambiental','Compuestos orgánicos volátiles, semivolátiles, aniones y cationes.','GC-MS · IC · PURGA Y TRAMPA','/industrias/ambiental'],['Farmacéutica','Ensayo, impurezas, estabilidad, disolución y cumplimiento documental.','HPLC · UHPLC · IQ/OQ/PQ','/industrias/farmaceutica'],['Academia e investigación','Docencia, desarrollo de métodos e instrumentación para investigación.','GC · HPLC · ESPECTROSCOPÍA','/industrias/academia'],['Industrial y energía','Gases, hidrocarburos, solventes, agua de proceso y materiales.','GC · PFPD · TEA · IC','/industrias']];return <><PageHero crumb="Industrias" eyebrow="Aplicaciones por sector" title="Empieza por tu objetivo, no por el catálogo." lead="Cada sector llega a sus aplicaciones, a los equipos que puede implementar y al servicio que sostiene la operación."/><section className="section"><div className="container grid-3">{inds.map(i=><Link className="card accent" href={i[3]} key={i[0]}><span className="caps">{i[2]}</span><h3>{i[0]}</h3><p>{i[1]}</p><span className="text-link">Ver la colección →</span></Link>)}</div></section></>}

export function IndustryDetail({industry='bebidas alcohólicas'}:{industry?:string}){return <><PageHero crumb="Industrias" eyebrow="Industria" title={`Instrumentación y soporte para laboratorios de ${industry}.`} lead="Furfural, azúcares, alcoholes superiores, perfiles de destilado y aplicaciones de cerveza. Configuramos el sistema, montamos el método y sostenemos la operación del laboratorio." cta="Consultar mi laboratorio por WhatsApp"/><section className="section"><div className="container grid-2"><div className="stack"><h2>Retos del sector</h2><ul className="feature-list"><li>Liberar lotes sin depender del calendario de un tercero</li><li>Comparar resultados entre campañas y líneas</li><li>Cumplir método, norma y trazabilidad documental</li><li>Mantener sistemas de distintas marcas en operación</li></ul></div><Empty text="Laboratorio de bebidas con el equipo y la aplicación identificados."/></div></section><section className="section tint"><div className="container stack-lg"><div className="stack"><span className="eyebrow">Aplicaciones</span><h2>Aplicaciones que puedes implementar en tu laboratorio</h2><p className="lead">La técnica indicada es orientativa. La ficha de cada aplicación establece la ruta, sus fuentes y sus limitaciones.</p></div><div className="grid-3"><Card meta="HPLC · UV + RID" title="Furfural y azúcares en tequila" text="Determinación simultánea para control de lote y liberación de producto." href="/aplicaciones/furfural-azucares-tequila"/><Card meta="GC · FID" title="Alcoholes superiores y congéneres" text="Perfil de compuestos volátiles para comparación entre lotes."/><Card meta="GC · Headspace" title="Metanol en bebidas alcohólicas" text="Determinación con inyección de espacio de cabeza."/></div></div></section><section className="section"><div className="container grid-2"><article className="card accent"><h4>Equipos y soluciones asociadas</h4>{['ChroZen HPLC con detección UV y RID','ChroZen GC con FID y headspace','Detección TEA de Ellutia para aplicación cervecera','Columnas y consumibles para las determinaciones'].map(x=><span className="list-line" key={x}>{x}<b className="text-link">→</b></span>)}</article><article className="card"><h4>Montaje y servicio para este sector</h4><p>Configuración, instalación, montaje de condiciones, capacitación, IQ/OQ y mantenimiento.</p><Link className="text-link" href="/servicio">Ver todos los servicios →</Link></article></div></section></>}

export function Resources(){const rec=[['Checklist','Datos que conviene reunir antes de comprar una columna','Muestra, analitos, fase actual y dimensiones antes de pedir una referencia.','PDF · 2 páginas'],['Formato','Bitácora diaria para HPLC','Presión, línea base, incidencias y acciones para detectar cambios antes de una falla.','XLSX · editable'],['Guía','Información útil para reportar una falla','Síntoma, modelo, evidencia e historial que aceleran la primera conversación.','PDF · 1 página'],['Video','Cómo revisar fugas en un HPLC','Recorrido visual por conexiones, sellos y puntos de inspección.','Video · 12 min'],['Presentación','IQ, OQ y PQ: qué documenta cada calificación','Una explicación reutilizable para calidad, operación y compras.','PDF · 18 diapositivas'],['Checklist','Preparación del sitio para HPLC','Electricidad, gases, mesa, temperatura y condiciones de instalación.','PDF · 3 páginas']];return <><PageHero crumb="Recursos gratuitos" eyebrow="Conocimiento de campo" title="Material que usamos en campo, disponible para tu laboratorio." lead="Checklists, formatos de bitácora, guías de método, videos de mantenimiento y presentaciones que puedes reutilizar frente a tu equipo. Sin costo."/><section className="section"><div className="container grid-2"><Empty text="Técnico realizando mantenimiento de HPLC, grabado en laboratorio."/><div className="stack"><span className="eyebrow">Serie en video</span><h2>Mantenimiento de HPLC en seis capítulos</h2><p className="lead">De la revisión de fugas al cambio de sellos y la prueba de cierre. Grabado en laboratorio, con el detalle que un técnico necesita para repetirlo.</p><span className="text-link">Ver la serie completa →</span></div></div></section><section className="section tint"><div className="container stack-lg"><h2>Empieza por lo que necesitas resolver, no por el formato.</h2><div className="grid-3">{rec.map(r=><article className="card" key={r[1]}><span className="badge blue">{r[0]}</span><h4>{r[1]}</h4><p>{r[2]}</p><span className="caps">{r[3]}</span><span className="text-link">Ver recurso →</span></article>)}</div></div></section><section className="section dark"><div className="container row between responsive"><div className="stack"><h2>Dinos qué técnica o equipo te interesa y lo preparamos para el siguiente seminario.</h2><p className="lead">Respuesta técnica en menos de 2 horas en horario laboral.</p></div><a className="btn btn-wa" href={WA}>Escríbenos por WhatsApp</a></div></section></>}
