export type ApplicationDetailData = {
  slug:string
  industry:string
  technique:string
  title:string
  lead:string
  solves:string[]
  configuration:string[]
  notes:string
}

export const applications: Record<string,ApplicationDetailData> = {
  'alcoholes-superiores-congeneres': {slug:'alcoholes-superiores-congeneres',industry:'Bebidas alcohólicas',technique:'GC · FID',title:'Alcoholes superiores y congéneres',lead:'Perfil de compuestos volátiles para comparar lotes, materias primas y condiciones de destilación.',solves:['Comparar perfiles entre campañas','Detectar variaciones de fermentación y destilación','Documentar resultados para liberación de lote'],configuration:['ChroZen GC con detector FID','Automuestreador o inyección manual','Columna capilar para alcoholes y congéneres'],notes:'La columna, el estándar interno y las condiciones se ajustan a la matriz y al criterio de aceptación del laboratorio.'},
  'metanol-bebidas-alcoholicas': {slug:'metanol-bebidas-alcoholicas',industry:'Bebidas alcohólicas',technique:'GC · Headspace',title:'Metanol en bebidas alcohólicas',lead:'Determinación de metanol y otros compuestos volátiles mediante preparación de espacio de cabeza.',solves:['Reducir manipulación de muestras','Controlar límites de metanol en producto terminado','Obtener resultados repetibles entre lotes'],configuration:['GC con muestreador headspace','Detector FID','Estándares y viales compatibles con la matriz'],notes:'El método definitivo se establece con la bebida, el rango de trabajo y el límite de cuantificación requerido.'},
  'conservadores-edulcorantes': {slug:'conservadores-edulcorantes',industry:'Alimentos y bebidas',technique:'HPLC · UV/DAD',title:'Conservadores y edulcorantes',lead:'Cuantificación de aditivos para verificar formulación, especificaciones y liberación de producto.',solves:['Verificar concentración declarada','Comparar formulaciones y proveedores','Sostener control de calidad de producto terminado'],configuration:['HPLC con UV o DAD','Columna adecuada para la familia de aditivos','Preparación y filtración de muestra'],notes:'La selección de fase móvil y longitud de onda depende de los analitos y de la matriz.'},
  'aromas-sabores-volatiles': {slug:'aromas-sabores-volatiles',industry:'Alimentos y bebidas',technique:'GC-MS',title:'Aromas, sabores y compuestos volátiles',lead:'Perfil de compuestos volátiles para control sensorial, autenticidad y comparación de lotes.',solves:['Comparar perfiles aromáticos','Identificar compuestos marcadores','Apoyar desarrollo y control de formulaciones'],configuration:['GC-MS con biblioteca espectral','Preparación por headspace o extracción','Columna capilar para volátiles'],notes:'El tratamiento de muestra se define según el producto: bebidas, aceites, alimentos procesados o materias primas.'},
  'contaminantes-control-calidad': {slug:'contaminantes-control-calidad',industry:'Alimentos y bebidas',technique:'HPLC · GC-MS',title:'Contaminantes y control de calidad',lead:'Configuraciones analíticas para investigar contaminantes, adulteraciones y desviaciones en matrices de alimentos.',solves:['Revisar materias primas y producto terminado','Investigar desviaciones de calidad','Documentar resultados para auditorías'],configuration:['HPLC o GC-MS según el contaminante','Preparación de muestra adaptada a la matriz','Controles, blancos y materiales de referencia'],notes:'El alcance se define con el contaminante objetivo, la matriz y el límite regulatorio aplicable.'},
  'vocs-ambientales': {slug:'vocs-ambientales',industry:'Análisis ambiental',technique:'GC-MS · Purge & Trap',title:'VOCs en agua y matrices ambientales',lead:'Preparación automatizada y determinación de compuestos orgánicos volátiles en muestras ambientales.',solves:['Cumplir métodos EPA para VOCs','Mejorar sensibilidad y repetibilidad','Reducir tiempos de preparación'],configuration:['GC-MS','Sistema de purga y trampa','Automuestreo y estándares de control'],notes:'La configuración se ajusta al tipo de agua, al rango de concentración y al método de referencia.'},
  'svocs-contaminantes-organicos': {slug:'svocs-contaminantes-organicos',industry:'Análisis ambiental',technique:'GC-MS',title:'SVOCs y contaminantes orgánicos',lead:'Identificación y cuantificación de semivolátiles en agua, suelo, aire y residuos.',solves:['Investigar contaminación orgánica','Comparar sitios y campañas de muestreo','Generar evidencia trazable para reportes'],configuration:['GC-MS','Extracción y concentración de muestra','Columna y programa de horno para la familia objetivo'],notes:'La preparación depende de la matriz y de los límites de detección solicitados.'},
  'aniones-cationes-agua': {slug:'aniones-cationes-agua',industry:'Análisis ambiental',technique:'IC',title:'Aniones y cationes en agua',lead:'Cromatografía iónica para control de agua potable, residual y de proceso.',solves:['Verificar calidad de agua','Comparar entradas y salidas de tratamiento','Monitorear aniones y cationes con un método reproducible'],configuration:['Cromatógrafo iónico','Supresión de conductividad','Columnas específicas para aniones o cationes'],notes:'La configuración se define con los iones objetivo, el rango y la conductividad de la muestra.'},
  'ensayo-impurezas': {slug:'ensayo-impurezas',industry:'Industria farmacéutica',technique:'HPLC · UHPLC',title:'Ensayo e impurezas',lead:'Cuantificación de principio activo y perfiles de impurezas en producto terminado.',solves:['Liberar producto con resultados trazables','Controlar degradantes y subproductos','Transferir métodos entre equipos'],configuration:['HPLC o UHPLC con UV/DAD','Columna definida por la monografía o método','Software de adquisición e integración'],notes:'La verificación se realiza frente al método aprobado y a los criterios de aceptación del producto.'},
  'disolucion-producto': {slug:'disolucion-producto',industry:'Industria farmacéutica',technique:'Disolución · HPLC',title:'Liberación y desempeño del producto',lead:'Configuraciones para comparar perfiles de disolución y verificar especificaciones de calidad.',solves:['Comparar lotes y formulaciones','Documentar desempeño del producto','Apoyar desarrollo y transferencia de métodos'],configuration:['Equipo de disolución','Muestreo programado','HPLC con UV/DAD'],notes:'El medio, los tiempos y la filtración se establecen según el producto y el método aplicable.'},
  'estudios-estabilidad': {slug:'estudios-estabilidad',industry:'Industria farmacéutica',technique:'HPLC · Estabilidad',title:'Estudios de estabilidad',lead:'Seguimiento de degradantes y cambios del producto durante su vida útil.',solves:['Identificar rutas de degradación','Comparar condiciones de almacenamiento','Sostener estudios de estabilidad documentados'],configuration:['HPLC/UHPLC con detector UV o DAD','Columna de resolución adecuada','Control de temperatura y registro de condiciones'],notes:'El plan analítico se alinea con el protocolo de estabilidad y los tiempos de muestreo aprobados.'},
  'hplc-docencia': {slug:'hplc-docencia',industry:'Academia e investigación',technique:'HPLC · Docencia',title:'Prácticas de separación y cuantificación',lead:'Ejercicios de preparación de muestra, identificación y cuantificación para cursos y laboratorios de enseñanza.',solves:['Enseñar fundamentos de cromatografía','Practicar curvas de calibración','Formar operadores con buenas prácticas'],configuration:['HPLC modular','Detector UV','Columnas y consumibles de uso docente'],notes:'La configuración puede crecer desde prácticas básicas hacia proyectos de investigación.'},
  'compuestos-volatiles-investigacion': {slug:'compuestos-volatiles-investigacion',industry:'Academia e investigación',technique:'GC · Investigación',title:'Compuestos volátiles y perfiles de muestra',lead:'Análisis de mezclas, desarrollo de métodos y comparación de matrices para investigación aplicada.',solves:['Desarrollar métodos exploratorios','Comparar perfiles de muestras','Generar datos para tesis y publicaciones'],configuration:['GC con FID o MS','Columnas intercambiables','Muestreo manual o automático'],notes:'El alcance se adapta al nivel de identificación requerido y a la experiencia del grupo operador.'},
  'metodos-uv-vis-ensenanza': {slug:'metodos-uv-vis-ensenanza',industry:'Academia e investigación',technique:'UV-Vis · Espectroscopía',title:'Métodos instrumentales para enseñanza',lead:'Determinaciones accesibles para cursos, tesis y proyectos de investigación.',solves:['Introducir espectroscopía cuantitativa','Practicar leyes de absorción y calibración','Conectar teoría con análisis de muestras reales'],configuration:['Espectrofotómetro UV-Vis','Cubetas y accesorios de muestra','Software para curvas y resultados'],notes:'Las prácticas se pueden adaptar a química, alimentos, ambiental y ciencias de la salud.'},
  'hidrocarburos-gases-solventes': {slug:'hidrocarburos-gases-solventes',industry:'Industria y energía',technique:'GC · FID/TCD',title:'Hidrocarburos, gases y solventes',lead:'Separación y cuantificación para materias primas, producto y control de proceso.',solves:['Controlar composición de corrientes','Verificar materias primas y producto','Tomar decisiones de proceso con resultados oportunos'],configuration:['GC con FID, TCD o ambos','Inyección adecuada al tipo de muestra','Columnas para hidrocarburos y solventes'],notes:'La configuración se define con el rango, la fase y el tipo de corriente industrial.'},
  'compuestos-especificos-proceso': {slug:'compuestos-especificos-proceso',industry:'Industria y energía',technique:'GC · PFPD/TEA',title:'Compuestos específicos en proceso',lead:'Detección selectiva para azufrados, nitrógeno y otras familias de interés industrial.',solves:['Monitorear compuestos traza','Investigar desviaciones de proceso','Reducir interferencias de matrices complejas'],configuration:['GC con detector PFPD o TEA','Columna y acondicionamiento de muestra','Estándares para calibración selectiva'],notes:'El detector se selecciona con base en la familia química y el límite de detección requerido.'},
  'iones-agua-proceso': {slug:'iones-agua-proceso',industry:'Industria y energía',technique:'IC · Agua de proceso',title:'Iones y calidad del agua',lead:'Seguimiento de aniones y cationes en agua de proceso y servicios industriales.',solves:['Monitorear tratamiento y recirculación','Detectar cambios en calidad de agua','Apoyar mantenimiento y control operativo'],configuration:['Cromatógrafo iónico','Supresión de conductividad','Columnas para el panel de iones objetivo'],notes:'La frecuencia de análisis y el panel se definen con el proceso y los puntos de muestreo.'},
}

export function getApplication(slug:string){return applications[slug]}
