export {
  type Product,
  type ProductConfig,
  type CategoryData,
  type ProductDetail,
  type SolutionItem,
  type FilterGroup,
  solucionesFilters,
  overviewSpecRows,
  hplcProducts,
  categoriesMap,
  eliteSeriesDetail,
  productDetailsMap,
  solutionItems,
  filterConfig,
} from './soluciones-data';
